# Generated by Django 3.2.2 on 2021-05-22 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comun', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombres')),
                ('apellido', models.CharField(max_length=50, verbose_name='apellidos')),
                ('fecha_nacimiento', models.DateField(verbose_name='fecha nacimiento')),
                ('correo', models.EmailField(max_length=254, verbose_name='email')),
                ('nit', models.CharField(max_length=10, verbose_name='NIT')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
                'unique_together': {('nombre', 'apellido')},
            },
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(help_text='solo incluir numeros', verbose_name='numero de telefono')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente', verbose_name='Cliente')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TelCliente', to='comun.tipotelefono', verbose_name='Tipo Telefono')),
            ],
            options={
                'verbose_name': 'Telefono de Cliente',
                'verbose_name_plural': 'Telefono de Cliente',
            },
        ),
    ]
